#server:
#  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      enabled: false
      import-check:
        enabled: false
#
#eureka:
#  client:
#    register-with-eureka: false # tells Eureka don't register yourself
#    fetch-registry: false # tells Eureka don't fetch other MSs details, lets them register themselves with you
